HSTEP, VSTEP = 13, 18
WIDTH, HEIGHT = 800, 600

SCROLL_STEP = 100
LEADING_FACTOR = 1.25

INPUT_WIDTH_PX = 200

DEFAULT_FONT_SIZE_PX = 16

POINTER_HOVER_TAG = "pointer_hover"
CLEARABLE_CONTENT_TAG = "clearable"

